version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: shoe-store-api
    ports:
      - "5000:5000"
    env_file:
      - .env.production
    depends_on:
      - mongo

volumes:
  mongo-data:
